// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOeUq0N43luwhay7yyOdgYkr_yJ8QB_Is',
    appId: '1:1046227288727:web:1bdd70859d08b685409fd2',
    messagingSenderId: '1046227288727',
    projectId: 'dulieumoitruong-e3085',
    authDomain: 'dulieumoitruong-e3085.firebaseapp.com',
    databaseURL: 'https://dulieumoitruong-e3085-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dulieumoitruong-e3085.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClyprY_SNEDvanyKS7MJ3oXggLwm9Vl_s',
    appId: '1:1046227288727:android:e08dca4529ced1ae409fd2',
    messagingSenderId: '1046227288727',
    projectId: 'dulieumoitruong-e3085',
    databaseURL: 'https://dulieumoitruong-e3085-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dulieumoitruong-e3085.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA__I-aPlKH881K5UHu2A0ISobkggsu26g',
    appId: '1:1046227288727:ios:43519dedd41dab6a409fd2',
    messagingSenderId: '1046227288727',
    projectId: 'dulieumoitruong-e3085',
    databaseURL: 'https://dulieumoitruong-e3085-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dulieumoitruong-e3085.firebasestorage.app',
    iosBundleId: 'com.example.dlmt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA__I-aPlKH881K5UHu2A0ISobkggsu26g',
    appId: '1:1046227288727:ios:43519dedd41dab6a409fd2',
    messagingSenderId: '1046227288727',
    projectId: 'dulieumoitruong-e3085',
    databaseURL: 'https://dulieumoitruong-e3085-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dulieumoitruong-e3085.firebasestorage.app',
    iosBundleId: 'com.example.dlmt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOeUq0N43luwhay7yyOdgYkr_yJ8QB_Is',
    appId: '1:1046227288727:web:f72cdda1f72282f9409fd2',
    messagingSenderId: '1046227288727',
    projectId: 'dulieumoitruong-e3085',
    authDomain: 'dulieumoitruong-e3085.firebaseapp.com',
    databaseURL: 'https://dulieumoitruong-e3085-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dulieumoitruong-e3085.firebasestorage.app',
  );

}